"""Models for RMP source files with `tblS7...` prefix."""
from django.db import models
from rmp.fields import (
    CopyFromBigIntegerField,
    CopyFromBooleanField,
    CopyFromCharField,
    CopyFromDateTimeField,
    CopyFromDecimalField,
    CopyFromForeignKey,
    CopyFromIntegerField,
    CopyFromTextField,
)
from rmp.models.base import BaseRMPModel


class tblS7PreventionProgramChemicals(BaseRMPModel):
    PrimaryKey = CopyFromIntegerField(
        primary_key=True,
        verbose_name='Primary Key',
        help_text='Unique identifier for the Prevention Program 3 chemicals '
                  'record destination table. Generated by RMP*Submit and 3rd-'
                  'party programs.',
    )
    PreventionProgram3ID = CopyFromForeignKey(
        'Tbls7PreventionProgram3',
        db_column='PreventionProgram3ID',
        verbose_name='Prevention Program 3 ID',
        on_delete=models.PROTECT,
        help_text='A unique number used to identify each prevention program '
                  'within a NAICS code within a process. Generated by '
                  'RMP*Submit and 3rd-party programs.',
    )
    ProcessChemicalID = CopyFromForeignKey(
        'tbls1ProcessChemicals',
        db_column='ProcessChemicalID',
        on_delete=models.PROTECT,
        verbose_name='Process Chemical ID',
        help_text='A number used to identify each chemical within a single RMP'
                  'from Section 1 Chemicals in Covered Process. Generated by '
                  'RMP*Submit and 3rd-party programs.'
    )

    source_file = 'tblS7_Prevention_Program_Chemicals'

    class Meta:
        verbose_name = 'Prevention Program: Program Level 3 Chemical'
        verbose_name_plural = 'Prevention Program: Program Level 3 Chemical'


class tblS7PreventionProgramChemicalsChangeHistory(BaseRMPModel):
    PP3ChemChangeHistoryID = CopyFromIntegerField(
        primary_key=True,
        verbose_name='PP3 Chemical Change History ID',
    )
    FacilityChangeHistoryID = CopyFromIntegerField(
        verbose_name='Facility Change History ID',
    )
    CDXCorrectionCode = CopyFromCharField(
        max_length=1,
        verbose_name='CDX Correction Code',
    )
    PP3ChemID = CopyFromForeignKey(
        'tblS7PreventionProgramChemicals',
        db_column='PP3ChemID',
        on_delete=models.PROTECT,
        verbose_name='Prevention Program Chemical ID',
    )
    PreventionProgram3ID = CopyFromForeignKey(
        'tblS7PreventionProgram3',
        db_column='PreventionProgram3ID',
        on_delete=models.PROTECT,
        verbose_name='Prevention Program3 ID',
    )
    ProcessChemicalID = CopyFromForeignKey(
        'tblS1ProcessChemicals',
        db_column='ProcessChemicalID',
        on_delete=models.PROTECT,
        verbose_name='Process Chemical ID',
    )
    process_naics_id = CopyFromForeignKey(
        'tblS1Process_NAICS',
        db_column='process_naics_id',
        on_delete=models.PROTECT,
        verbose_name='',
    )
    NAICSCode = CopyFromForeignKey(
        'tlkpNAICS',
        db_column='NAICSCode',
        on_delete=models.PROTECT,
        verbose_name='NAICS Code',
    )

    source_file = 'tblS7_Prevention_Program_Chemicals_ChangeHistory'


class tblS7PreventionProgram3(BaseRMPModel):
    PreventionProgram3ID = CopyFromIntegerField(
        primary_key=True,
    )
    Process_NAICS_ID = CopyFromForeignKey(
        'tblS1Process_NAICS',
        db_column='Process_NAICS_ID',
        on_delete=models.PROTECT,
    )
    SafetyReviewDate = CopyFromDateTimeField(
        null=True,
    )
    PHA_Date = CopyFromDateTimeField(
        null=True,
    )
    PHA_WhatIf = CopyFromBooleanField(
    )
    PHA_Checklist = CopyFromBooleanField(
    )
    PHA_WhatIfChecklist = CopyFromBooleanField(
    )
    PHA_HAZOP = CopyFromBooleanField(
    )
    PHA_FMEA = CopyFromBooleanField(
    )
    PHA_FTA = CopyFromBooleanField(
    )
    PHA_OtherTechnique = CopyFromCharField(
        max_length=200,
        blank=True,
    )
    PHACompletionDate = CopyFromDateTimeField(
        null=True,
    )
    MH_ToxicRelease = CopyFromBooleanField(
    )
    MH_Fire = CopyFromBooleanField(
    )
    MH_Explosion = CopyFromBooleanField(
    )
    MH_RunawayReaction = CopyFromBooleanField(
    )
    MH_Polymerization = CopyFromBooleanField(
    )
    MH_Overpressurization = CopyFromBooleanField(
    )
    MH_Corrosion = CopyFromBooleanField(
    )
    MH_Overfilling = CopyFromBooleanField(
    )
    MH_Contamination = CopyFromBooleanField(
    )
    MH_EquipmentFailure = CopyFromBooleanField(
    )
    MH_CoolingLoss = CopyFromBooleanField(
    )
    MH_Earthquake = CopyFromBooleanField(
    )
    MH_Floods = CopyFromBooleanField(
    )
    MH_Tornado = CopyFromBooleanField(
    )
    MH_Hurricanes = CopyFromBooleanField(
    )
    MH_OtherType = CopyFromCharField(
        max_length=200,
        blank=True,
    )
    PC_Vents = CopyFromBooleanField(
    )
    PC_ReliefValves = CopyFromBooleanField(
    )
    PC_CheckValves = CopyFromBooleanField(
    )
    PC_Scrubbers = CopyFromBooleanField(
    )
    PC_Flares = CopyFromBooleanField(
    )
    PC_ManualShutoffs = CopyFromBooleanField(
    )
    PC_AutomaticShutoffs = CopyFromBooleanField(
    )
    PC_Interlocks = CopyFromBooleanField(
    )
    PC_Alarms = CopyFromBooleanField(
    )
    PC_KeyedBypass = CopyFromBooleanField(
    )
    PC_EmergencyAirSupply = CopyFromBooleanField(
    )
    PC_EmergencyPower = CopyFromBooleanField(
    )
    PC_BackupPump = CopyFromBooleanField(
    )
    PC_GroundingEquipment = CopyFromBooleanField(
    )
    PC_InhibitorAddition = CopyFromBooleanField(
    )
    PC_RuptureDisks = CopyFromBooleanField(
    )
    PC_ExcessFlowDevice = CopyFromBooleanField(
    )
    PC_QuenchSystem = CopyFromBooleanField(
    )
    PC_PurgeSystem = CopyFromBooleanField(
    )
    PC_None = CopyFromBooleanField(
    )
    PC_OtherType = CopyFromCharField(
        max_length=200,
        blank=True,
    )
    MS_SprinklerSystem = CopyFromBooleanField(
    )
    MS_Dikes = CopyFromBooleanField(
    )
    MS_FireWalls = CopyFromBooleanField(
    )
    MS_BlastWalls = CopyFromBooleanField(
    )
    MS_DelugeSystem = CopyFromBooleanField(
    )
    MS_WaterCurtain = CopyFromBooleanField(
    )
    MS_Enclosure = CopyFromBooleanField(
    )
    MS_Neutralization = CopyFromBooleanField(
    )
    MS_None = CopyFromBooleanField(
    )
    MS_OtherType = CopyFromCharField(
        max_length=200,
        blank=True,
    )
    MD_ProcessAreaDetectors = CopyFromBooleanField(
    )
    MD_PerimeterMonitors = CopyFromBooleanField(
    )
    MD_None = CopyFromBooleanField(
    )
    MD_OtherType = CopyFromCharField(
        max_length=200,
        blank=True,
    )
    CH_ChemicalReduction = CopyFromBooleanField(
    )
    CH_ChemicalIncrease = CopyFromBooleanField(
    )
    CH_ChangeProcessParameters = CopyFromBooleanField(
    )
    CH_InstallProcessControls = CopyFromBooleanField(
    )
    CH_InstallProcessDetection = CopyFromBooleanField(
    )
    CH_InstallPerimeterMonitoring = CopyFromBooleanField(
    )
    CH_InstallMitigationSystems = CopyFromBooleanField(
    )
    CH_NoneRequired = CopyFromBooleanField(
    )
    CH_None = CopyFromBooleanField(
    )
    CH_OtherChanges = CopyFromCharField(
        max_length=200,
        blank=True,
    )
    OpProceduresReviewDate = CopyFromDateTimeField(
        null=True,
    )
    TrainingReviewDate = CopyFromDateTimeField(
        null=True,
    )
    TR_Classroom = CopyFromBooleanField(
    )
    TR_OnTheJob = CopyFromBooleanField(
    )
    TR_OtherType = CopyFromCharField(
        max_length=200,
        blank=True,
    )
    CT_WrittenTest = CopyFromBooleanField(
    )
    CT_OralTest  = CopyFromBooleanField(
    )
    CT_Demonstration = CopyFromBooleanField(
    )
    CT_Observation = CopyFromBooleanField(
    )
    CT_OtherType = CopyFromCharField(
        max_length=200, blank=True
    )
    MaintenanceReviewDate = CopyFromDateTimeField(
        null=True,
    )
    EquipmentInspectionDate = CopyFromDateTimeField(
        null=True,
    )
    EquipmentTested = CopyFromCharField(
        max_length=200,
        blank=True,
    )
    ChangeMgmtDate = CopyFromDateTimeField(
        null=True,
    )
    ChangeMgmtReviewDate = CopyFromDateTimeField(
        null=True,
    )
    PreStartupReviewDate = CopyFromDateTimeField(
        null=True,
    )
    ComplianceAuditDate = CopyFromDateTimeField(
        null=True,
    )
    AuditCompletionDate = CopyFromDateTimeField(
        null=True,
    )
    IncidentInvestigationDate = CopyFromDateTimeField(
        null=True,
    )
    InvestigationChangeDate = CopyFromDateTimeField(
        null=True,
    )
    ParticipationPlansReviewDate = CopyFromDateTimeField(
        null=True,
    )
    HotWorkPermitReviewDate = CopyFromDateTimeField(
        null=True,
    )
    ContractorSafetyReviewDate = CopyFromDateTimeField(
        null=True,
    )
    ContractorSafetyEvalDate = CopyFromDateTimeField(
        null=True,
    )
    CBI_Flag = CopyFromBooleanField(
    )
    Description = CopyFromTextField(
        blank=True,
    ) # TODO to rmp_prev3text with prevention programID

    class Meta:
        verbose_name = 'Prevention Program: Program Level 3'
        verbose_name_plural = 'Prevention Programs: Program Level 3'


class tblS7PreventionProgram3Description_ChangeHistory(BaseRMPModel):
    PreventionProgram3DescChangeHistoryID = CopyFromIntegerField(
        primary_key=True,
    )
    FacilityChangeHistoryID = CopyFromIntegerField(
    )
    CDXCorrectionCode = CopyFromCharField(
        max_length=1,
    )
    PreventionProgram3ID = CopyFromForeignKey(
        'tblS7PreventionProgram3',
        db_column='PreventionProgram3ID',
        on_delete=models.PROTECT,
    )
    Description = CopyFromTextField(
        blank=True,
    )
    OldDescription = CopyFromTextField(
        blank=True,
    )
    SeqNum = CopyFromIntegerField(
    )


# class tblS7PreventionProgram3_ChangeHistory(BaseRMPModel):
    # preventionprogram3changehistoryid = (
    #     source_column='PreventionProgram3ChangeHistoryID',
    # )
    # facilitychangehistoryid = (
    #     source_column='FacilityChangeHistoryID',
    # )
    # cdxcorrectioncode = (
    #     source_column='CDXCorrectionCode',
    # )
    # preventionprogram3id = (
    #     source_column='PreventionProgram3ID',
    # )
    # naicscode = (
    #     source_column='NAICSCode',
    # )
    # process_naics_id = (
    #     source_column='Process_NAICS_ID',
    # )
    # processid = (
    #     source_column='ProcessID',
    # )
    # safetyreviewdate = (
    #     source_column='SafetyReviewDate',
    # )
    # oldsafetyreviewdate = (
    #     source_column='OldSafetyReviewDate',
    # )
    # pha_date = (
    #     source_column='PHA_Date',
    # )
    # oldpha_date = (
    #     source_column='OldPHA_Date',
    # )
    # pha_whatif = (
    #     source_column='PHA_WhatIf',
    # )
    # oldpha_whatif = (
    #     source_column='OldPHA_WhatIf',
    # )
    # pha_checklist = (
    #     source_column='PHA_Checklist',
    # )
    # oldpha_checklist = (
    #     source_column='OldPHA_Checklist',
    # )
    # pha_whatifchecklist = (
    #     source_column='PHA_WhatIfChecklist',
    # )
    # oldpha_whatifchecklist = (
    #     source_column='OldPHA_WhatIfChecklist',
    # )
    # pha_hazop = (
    #     source_column='PHA_HAZOP',
    # )
    # oldpha_hazop = (
    #     source_column='OldPHA_HAZOP',
    # )
    # pha_fmea = (
    #     source_column='PHA_FMEA',
    # )
    # oldpha_fmea = (
    #     source_column='OldPHA_FMEA',
    # )
    # pha_fta = (
    #     source_column='PHA_FTA',
    # )
    # oldpha_fta = (
    #     source_column='OldPHA_FTA',
    # )
    # pha_othertechnique = (
    #     source_column='PHA_OtherTechnique',
    # )
    # oldpha_othertechnique = (
    #     source_column='OldPHA_OtherTechnique',
    # )
    # phacompletiondate = (
    #     source_column='PHACompletionDate',
    # )
    # oldphacompletiondate = (
    #     source_column='OldPHACompletionDate',
    # )
    # mh_toxicrelease = (
    #     source_column='MH_ToxicRelease',
    # )
    # oldmh_toxicrelease = (
    #     source_column='OldMH_ToxicRelease',
    # )
    # mh_fire = (
    #     source_column='MH_Fire',
    # )
    # oldmh_fire = (
    #     source_column='OldMH_Fire',
    # )
    # mh_explosion = (
    #     source_column='MH_Explosion',
    # )
    # oldmh_explosion = (
    #     source_column='OldMH_Explosion',
    # )
    # mh_runawayreaction = (
    #     source_column='MH_RunawayReaction',
    # )
    # oldmh_runawayreaction = (
    #     source_column='OldMH_RunawayReaction',
    # )
    # mh_polymerization = (
    #     source_column='MH_Polymerization',
    # )
    # oldmh_polymerization = (
    #     source_column='OldMH_Polymerization',
    # )
    # mh_overpressurization = (
    #     source_column='MH_Overpressurization',
    # )
    # oldmh_overpressurization = (
    #     source_column='OldMH_Overpressurization',
    # )
    # mh_corrosion = (
    #     source_column='MH_Corrosion',
    # )
    # oldmh_corrosion = (
    #     source_column='OldMH_Corrosion',
    # )
    # mh_overfilling = (
    #     source_column='MH_Overfilling',
    # )
    # oldmh_overfilling = (
    #     source_column='OldMH_Overfilling',
    # )
    # mh_contamination = (
    #     source_column='MH_Contamination',
    # )
    # oldmh_contamination = (
    #     source_column='OldMH_Contamination',
    # )
    # mh_equipmentfailure = (
    #     source_column='MH_EquipmentFailure',
    # )
    # oldmh_equipmentfailure = (
    #     source_column='OldMH_EquipmentFailure',
    # )
    # mh_coolingloss = (
    #     source_column='MH_CoolingLoss',
    # )
    # oldmh_coolingloss = (
    #     source_column='OldMH_CoolingLoss',
    # )
    # mh_earthquake = (
    #     source_column='MH_Earthquake',
    # )
    # oldmh_earthquake = (
    #     source_column='OldMH_Earthquake',
    # )
    # mh_floods = (
    #     source_column='MH_Floods',
    # )
    # oldmh_floods = (
    #     source_column='OldMH_Floods',
    # )
    # mh_tornado = (
    #     source_column='MH_Tornado',
    # )
    # oldmh_tornado = (
    #     source_column='OldMH_Tornado',
    # )
    # mh_hurricanes = (
    #     source_column='MH_Hurricanes',
    # )
    # oldmh_hurricanes = (
    #     source_column='OldMH_Hurricanes',
    # )
    # mh_othertype = (
    #     source_column='MH_OtherType',
    # )
    # oldmh_othertype = (
    #     source_column='OldMH_OtherType',
    # )
    # pc_vents = (
    #     source_column='PC_Vents',
    # )
    # oldpc_vents = (
    #     source_column='OldPC_Vents',
    # )
    # pc_reliefvalves = (
    #     source_column='PC_ReliefValves',
    # )
    # oldpc_reliefvalves = (
    #     source_column='OldPC_ReliefValves',
    # )
    # pc_checkvalves = (
    #     source_column='PC_CheckValves',
    # )
    # oldpc_checkvalves = (
    #     source_column='OldPC_CheckValves',
    # )
    # pc_scrubbers = (
    #     source_column='PC_Scrubbers',
    # )
    # oldpc_scrubbers = (
    #     source_column='OldPC_Scrubbers',
    # )
    # pc_flares = (
    #     source_column='PC_Flares',
    # )
    # oldpc_flares = (
    #     source_column='OldPC_Flares',
    # )
    # pc_manualshutoffs = (
    #     source_column='PC_ManualShutoffs',
    # )
    # oldpc_manualshutoffs = (
    #     source_column='OldPC_ManualShutoffs',
    # )
    # pc_automaticshutoffs = (
    #     source_column='PC_AutomaticShutoffs',
    # )
    # oldpc_automaticshutoffs = (
    #     source_column='OldPC_AutomaticShutoffs',
    # )
    # pc_interlocks = (
    #     source_column='PC_Interlocks',
    # )
    # oldpc_interlocks = (
    #     source_column='OldPC_Interlocks',
    # )
    # pc_alarms = (
    #     source_column='PC_Alarms',
    # )
    # oldpc_alarms = (
    #     source_column='OldPC_Alarms',
    # )
    # pc_keyedbypass = (
    #     source_column='PC_KeyedBypass',
    # )
    # oldpc_keyedbypass = (
    #     source_column='OldPC_KeyedBypass',
    # )
    # pc_emergencyairsupply = (
    #     source_column='PC_EmergencyAirSupply',
    # )
    # oldpc_emergencyairsupply = (
    #     source_column='OldPC_EmergencyAirSupply',
    # )
    # pc_emergencypower = (
    #     source_column='PC_EmergencyPower',
    # )
    # oldpc_emergencypower = (
    #     source_column='OldPC_EmergencyPower',
    # )
    # pc_backuppump = (
    #     source_column='PC_BackupPump',
    # )
    # oldpc_backuppump = (
    #     source_column='OldPC_BackupPump',
    # )
    # pc_groundingequipment = (
    #     source_column='PC_GroundingEquipment',
    # )
    # oldpc_groundingequipment = (
    #     source_column='OldPC_GroundingEquipment',
    # )
    # pc_inhibitoraddition = (
    #     source_column='PC_InhibitorAddition',
    # )
    # oldpc_inhibitoraddition = (
    #     source_column='OldPC_InhibitorAddition',
    # )
    # pc_rupturedisks = (
    #     source_column='PC_RuptureDisks',
    # )
    # oldpc_rupturedisks = (
    #     source_column='OldPC_RuptureDisks',
    # )
    # pc_excessflowdevice = (
    #     source_column='PC_ExcessFlowDevice',
    # )
    # oldpc_excessflowdevice = (
    #     source_column='OldPC_ExcessFlowDevice',
    # )
    # pc_quenchsystem = (
    #     source_column='PC_QuenchSystem',
    # )
    # oldpc_quenchsystem = (
    #     source_column='OldPC_QuenchSystem',
    # )
    # pc_purgesystem = (
    #     source_column='PC_PurgeSystem',
    # )
    # oldpc_purgesystem = (
    #     source_column='OldPC_PurgeSystem',
    # )
    # pc_none = (
    #     source_column='PC_None',
    # )
    # oldpc_none = (
    #     source_column='OldPC_None',
    # )
    # pc_othertype = (
    #     source_column='PC_OtherType',
    # )
    # oldpc_othertype = (
    #     source_column='OldPC_OtherType',
    # )
    # ms_sprinklersystem = (
    #     source_column='MS_SprinklerSystem',
    # )
    # oldms_sprinklersystem = (
    #     source_column='OldMS_SprinklerSystem',
    # )
    # ms_dikes = (
    #     source_column='MS_Dikes',
    # )
    # oldms_dikes = (
    #     source_column='OldMS_Dikes',
    # )
    # ms_firewalls = (
    #     source_column='MS_FireWalls',
    # )
    # oldms_firewalls = (
    #     source_column='OldMS_FireWalls',
    # )
    # ms_blastwalls = (
    #     source_column='MS_BlastWalls',
    # )
    # oldms_blastwalls = (
    #     source_column='OldMS_BlastWalls',
    # )
    # ms_delugesystem = (
    #     source_column='MS_DelugeSystem',
    # )
    # oldms_delugesystem = (
    #     source_column='OldMS_DelugeSystem',
    # )
    # ms_watercurtain = (
    #     source_column='MS_WaterCurtain',
    # )
    # oldms_watercurtain = (
    #     source_column='OldMS_WaterCurtain',
    # )
    # ms_enclosure = (
    #     source_column='MS_Enclosure',
    # )
    # oldms_enclosure = (
    #     source_column='OldMS_Enclosure',
    # )
    # ms_neutralization = (
    #     source_column='MS_Neutralization',
    # )
    # oldms_neutralization = (
    #     source_column='OldMS_Neutralization',
    # )
    # ms_none = (
    #     source_column='MS_None',
    # )
    # oldms_none = (
    #     source_column='OldMS_None',
    # )
    # ms_othertype = (
    #     source_column='MS_OtherType',
    # )
    # oldms_othertype = (
    #     source_column='OldMS_OtherType',
    # )
    # md_processareadetectors = (
    #     source_column='MD_ProcessAreaDetectors',
    # )
    # oldmd_processareadetectors = (
    #     source_column='OldMD_ProcessAreaDetectors',
    # )
    # md_perimetermonitors = (
    #     source_column='MD_PerimeterMonitors',
    # )
    # oldmd_perimetermonitors = (
    #     source_column='OldMD_PerimeterMonitors',
    # )
    # md_none = (
    #     source_column='MD_None',
    # )
    # oldmd_none = (
    #     source_column='OldMD_None',
    # )
    # md_othertype = (
    #     source_column='MD_OtherType',
    # )
    # oldmd_othertype = (
    #     source_column='OldMD_OtherType',
    # )
    # ch_chemicalreduction = (
    #     source_column='CH_ChemicalReduction',
    # )
    # oldch_chemicalreduction = (
    #     source_column='OldCH_ChemicalReduction',
    # )
    # ch_chemicalincrease = (
    #     source_column='CH_ChemicalIncrease',
    # )
    # oldch_chemicalincrease = (
    #     source_column='OldCH_ChemicalIncrease',
    # )
    # ch_changeprocessparameters = (
    #     source_column='CH_ChangeProcessParameters',
    # )
    # oldch_changeprocessparameters = (
    #     source_column='OldCH_ChangeProcessParameters',
    # )
    # ch_installprocesscontrols = (
    #     source_column='CH_InstallProcessControls',
    # )
    # oldch_installprocesscontrols = (
    #     source_column='OldCH_InstallProcessControls',
    # )
    # ch_installprocessdetection = (
    #     source_column='CH_InstallProcessDetection',
    # )
    # oldch_installprocessdetection = (
    #     source_column='OldCH_InstallProcessDetection',
    # )
    # ch_installperimetermonitoring = (
    #     source_column='CH_InstallPerimeterMonitoring',
    # )
    # oldch_installperimetermonitoring = (
    #     source_column='OldCH_InstallPerimeterMonitoring',
    # )
    # ch_installmitigationsystems = (
    #     source_column='CH_InstallMitigationSystems',
    # )
    # oldch_installmitigationsystems = (
    #     source_column='OldCH_InstallMitigationSystems',
    # )
    # ch_nonerequired = (
    #     source_column='CH_NoneRequired',
    # )
    # oldch_nonerequired = (
    #     source_column='OldCH_NoneRequired',
    # )
    # ch_none = (
    #     source_column='CH_None',
    # )
    # oldch_none = (
    #     source_column='OldCH_None',
    # )
    # ch_otherchanges = (
    #     source_column='CH_OtherChanges',
    # )
    # oldch_otherchanges = (
    #     source_column='OldCH_OtherChanges',
    # )
    # opproceduresreviewdate = (
    #     source_column='OpProceduresReviewDate',
    # )
    # oldopproceduresreviewdate = (
    #     source_column='OldOpProceduresReviewDate',
    # )
    # trainingreviewdate = (
    #     source_column='TrainingReviewDate',
    # )
    # oldtrainingreviewdate = (
    #     source_column='OldTrainingReviewDate',
    # )
    # tr_classroom = (
    #     source_column='TR_Classroom',
    # )
    # oldtr_classroom = (
    #     source_column='OldTR_Classroom',
    # )
    # tr_onthejob = (
    #     source_column='TR_OnTheJob',
    # )
    # oldtr_onthejob = (
    #     source_column='OldTR_OnTheJob',
    # )
    # tr_othertype = (
    #     source_column='TR_OtherType',
    # )
    # oldtr_othertype = (
    #     source_column='OldTR_OtherType',
    # )
    # ct_writtentest = (
    #     source_column='CT_WrittenTest',
    # )
    # oldct_writtentest = (
    #     source_column='OldCT_WrittenTest',
    # )
    # ct_oraltest = (
    #     source_column='CT_OralTest',
    # )
    # oldct_oraltest = (
    #     source_column='OldCT_OralTest',
    # )
    # ct_demonstration = (
    #     source_column='CT_Demonstration',
    # )
    # oldct_demonstration = (
    #     source_column='OldCT_Demonstration',
    # )
    # ct_observation = (
    #     source_column='CT_Observation',
    # )
    # oldct_observation = (
    #     source_column='OldCT_Observation',
    # )
    # ct_othertype = (
    #     source_column='CT_OtherType',
    # )
    # oldct_othertype = (
    #     source_column='OldCT_OtherType',
    # )
    # maintenancereviewdate = (
    #     source_column='MaintenanceReviewDate',
    # )
    # oldmaintenancereviewdate = (
    #     source_column='OldMaintenanceReviewDate',
    # )
    # equipmentinspectiondate = (
    #     source_column='EquipmentInspectionDate',
    # )
    # oldequipmentinspectiondate = (
    #     source_column='OldEquipmentInspectionDate',
    # )
    # equipmenttested = (
    #     source_column='EquipmentTested',
    # )
    # oldequipmenttested = (
    #     source_column='OldEquipmentTested',
    # )
    # changemgmtdate = (
    #     source_column='ChangeMgmtDate',
    # )
    # oldchangemgmtdate = (
    #     source_column='OldChangeMgmtDate',
    # )
    # changemgmtreviewdate = (
    #     source_column='ChangeMgmtReviewDate',
    # )
    # oldchangemgmtreviewdate = (
    #     source_column='OldChangeMgmtReviewDate',
    # )
    # prestartupreviewdate = (
    #     source_column='PreStartupReviewDate',
    # )
    # oldprestartupreviewdate = (
    #     source_column='OldPreStartupReviewDate',
    # )
    # complianceauditdate = (
    #     source_column='ComplianceAuditDate',
    # )
    # oldcomplianceauditdate = (
    #     source_column='OldComplianceAuditDate',
    # )
    # auditcompletiondate = (
    #     source_column='AuditCompletionDate',
    # )
    # oldauditcompletiondate = (
    #     source_column='OldAuditCompletionDate',
    # )
    # incidentinvestigationdate = (
    #     source_column='IncidentInvestigationDate',
    # )
    # oldincidentinvestigationdate = (
    #     source_column='OldIncidentInvestigationDate',
    # )
    # investigationchangedate = (
    #     source_column='InvestigationChangeDate',
    # )
    # oldinvestigationchangedate = (
    #     source_column='OldInvestigationChangeDate',
    # )
    # participationplansreviewdate = (
    #     source_column='ParticipationPlansReviewDate',
    # )
    # oldparticipationplansreviewdate = (
    #     source_column='OldParticipationPlansReviewDate',
    # )
    # hotworkpermitreviewdate = (
    #     source_column='HotWorkPermitReviewDate',
    # )
    # oldhotworkpermitreviewdate = (
    #     source_column='OldHotWorkPermitReviewDate',
    # )
    # contractorsafetyreviewdate = (
    #     source_column='ContractorSafetyReviewDate',
    # )
    # oldcontractorsafetyreviewdate = (
    #     source_column='OldContractorSafetyReviewDate',
    # )
    # contractorsafetyevaldate = (
    #     source_column='ContractorSafetyEvalDate',
    # )
    # oldcontractorsafetyevaldate = (
    #     source_column='OldContractorSafetyEvalDate',
    # )

    # class Meta:
    #     verbose_name=''
    #     verbose_name_plural=''
