# Generated by Django 2.1.1 on 2018-10-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accflam',
            name='id',
        ),
        migrations.AlterField(
            model_name='accflam',
            name='flammixchem_id',
            field=models.IntegerField(help_text='A unique ID for each flammable chemical record.', primary_key=True, serialize=False, verbose_name='Flammable Chemical ID'),
        ),
    ]
