# Generated by Django 2.1.1 on 2018-10-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0003_auto_20181005_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbls6accidentchemicals',
            name='accchem_id',
            field=models.IntegerField(db_column='accidentchemicalid', help_text='A unique ID for each accident chemical record.', primary_key=True, serialize=False, verbose_name='Accident Chemical Record ID'),
        ),
        migrations.AlterField(
            model_name='tbls6accidentchemicals',
            name='accident_id',
            field=models.IntegerField(db_column='accidenthistoryid', help_text='The unique ID for each accident record'),
        ),
        migrations.AlterField(
            model_name='tbls6accidentchemicals',
            name='chemical_id',
            field=models.IntegerField(db_column='chemicalid', help_text='The identifying ID for a particular chemical released in an accident.'),
        ),
        migrations.AlterField(
            model_name='tbls6accidentchemicals',
            name='percent_weight',
            field=models.DecimalField(db_column='percentweight', decimal_places=2, help_text='The percent weight of a chemical within a mixture released in an accident.', max_digits=5, null=True, verbose_name='Percent Weight (Within Mixture)'),
        ),
        migrations.AlterField(
            model_name='tbls6accidentchemicals',
            name='quantity_lbs',
            field=models.IntegerField(db_column='quantityreleased', help_text='The amount of the substance released in the accident, in pounds, to two significant digits.', verbose_name='Amount Released (lbs)'),
        ),
    ]
