# Generated by Django 2.1.1 on 2018-10-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0005_auto_20181005_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbls6accidentchemicals',
            name='quantity_lbs',
            field=models.DecimalField(decimal_places=6, help_text='The amount of the substance released in the accident, in pounds, to two significant digits.', max_digits=7, verbose_name='Amount Released (lbs)'),
        ),
    ]
